import React from 'react';
import { AlertCircle, CheckCircle2, Shield, Info } from 'lucide-react';
import FaqSection, { FaqItem } from '../common/FaqSection';

export default function DisclaimerPage() {
  const disclaimerFaqs: FaqItem[] = [
    {
      question: 'Why might a HEX color appear slightly different on another computer monitor or phone?',
      answer:
        'Display hardware varies widely in panel technology (IPS, OLED, TN), color gamut calibration (sRGB vs. Display P3), brightness, and operating system night-mode filters. The HEX code itself is mathematically exact, but how physical pixels render that value depends on the receiving screen. For print or strict brand standards, always verify colors with physical swatch books or proofs.',
    },
    {
      question: 'Why might Google Docs or Microsoft Word report a slightly different word count than this tool?',
      answer:
        'Different word processors use different parsing rules for punctuation, em-dashes, and hyphenated compound words (e.g. counting "user-friendly" as one word versus two). Our tool uses standard whitespace tokenization, which provides a fast, reliable approximation for digital drafting and word limit requirements.',
    },
    {
      question: 'Is a 16-character password generated by this tool guaranteed uncrackable?',
      answer:
        'A 16-character password generated via CSPRNG provides immense mathematical entropy against brute-force attacks. However, overall account security also depends on factors outside a password\'s complexity—such as whether the service encrypts credentials properly, whether you enable multi-factor authentication (MFA), and whether your local device is protected against keyloggers.',
    },
    {
      question: 'Can I publish the placeholder text as real website copy?',
      answer:
        'No. Lorem Ipsum is intentionally scrambled pseudo-Latin designed purely to simulate typographical density, line wrapping, and font sizing during wireframing. It carries no factual or linguistic meaning and should be replaced with real copy before a website or article is published.',
    },
    {
      question: 'Does Money Master Blog provide certified accessibility (WCAG) compliance audits?',
      answer:
        'No. While our Color Palette Generator provides relative contrast indicators, it is intended as a design brainstorming utility. Official accessibility compliance (WCAG 2.1 AA/AAA) requires testing your complete visual interface, including background hierarchy, font weights, and element sizing in context.',
    },
    {
      question: 'Does Money Master Blog offer legal, financial, or cryptographic advice?',
      answer:
        'No. Money Master Blog is an educational and productivity utility website. None of the tools, outputs, or commentary constitute legal advice, cybersecurity guarantees, or official engineering certifications.',
    },
    {
      question: 'Are the tutorials, regex patterns, and spreadsheet formulas in the Blog guaranteed for all software versions?',
      answer:
        'Our 20 guides reflect standard, well-tested spreadsheet formulas (Google Sheets, Microsoft 365) and established browser behavior. However, software updates, localized regional decimal settings (comma vs dot), and legacy application versions may cause slight syntax differences. We always recommend testing regex formulas or batch cleanups on a duplicate copy of your dataset first.',
    },
    {
      question: 'Can third-party browser extensions affect the output of these tools?',
      answer:
        'Yes. Aggressive browser extensions, grammar add-ons, or custom user-scripts running on your local browser may alter DOM elements or intercept clipboard actions. If you notice unexpected behavior, testing in an incognito or private browsing window can isolate extension interference.',
    },
    {
      question: 'What should I do if I discover a discrepancy or unexpected behavior in a tool?',
      answer:
        'Please report it to author Shahid Ali through our Contact Us page. We investigate all reported edge cases and algorithmic discrepancies promptly.',
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-12 space-y-10">
      <div className="border-b border-neutral-200 pb-8">
        <span className="text-xs font-semibold text-neutral-500 uppercase tracking-wider">
          Accuracy & Scope
        </span>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-neutral-900 tracking-tight mt-1">
          Website Disclaimer
        </h1>
        <p className="mt-2 text-sm text-neutral-600">
          Last updated: September 2026 • Published by Shahid Ali (7 years practical digital workflow experience)
        </p>
      </div>

      {/* Notice Banner */}
      <div className="p-5 rounded-xl bg-amber-50/70 border border-amber-200 flex items-start gap-4">
        <AlertCircle className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
        <div className="text-sm text-neutral-800 leading-relaxed">
          <strong>General Productivity Notice:</strong> The tools, calculations, and conversions provided on Money Master Blog are developed for general digital assistance, content drafting, design exploration, and everyday productivity. They are not intended as legal, cybersecurity audit, or mission-critical verification software.
        </div>
      </div>

      <div className="space-y-6 text-neutral-700 text-sm leading-relaxed">
        <div>
          <h2 className="text-lg font-bold text-neutral-900 mb-2">1. No Exaggerated Guarantees</h2>
          <p>
            Money Master Blog does not claim to be "the world's best", "100% infallible", or an "official" government or standards body utility. We believe in honest, practical craftsmanship. Shahid Ali maintains these utilities drawing upon 7 years of practical experience in digital content and web workflows, aiming to deliver dependable, convenient tools for everyday tasks.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-neutral-900 mb-2">2. Tool-Specific Technical Context</h2>
          <div className="space-y-3 mt-2">
            <div className="p-4 bg-white border border-neutral-200 rounded-lg">
              <strong className="text-neutral-900 block text-xs uppercase tracking-wider mb-1">Color Palette Generator</strong>
              <p className="text-xs text-neutral-600 leading-relaxed">
                Colors rendered on computer displays depend on individual screen calibrations, color profiles (sRGB vs Display P3), ambient lighting, and browser rendering engines. For industrial print production or strict corporate brand standards, physical color swatches and press proofs should always be consulted.
              </p>
            </div>

            <div className="p-4 bg-white border border-neutral-200 rounded-lg">
              <strong className="text-neutral-900 block text-xs uppercase tracking-wider mb-1">Text Cleaner & Case Converter</strong>
              <p className="text-xs text-neutral-600 leading-relaxed">
                Different word processors (such as Microsoft Word, Apple Pages, Google Docs, or LaTeX) employ differing tokenization algorithms for hyphenated compound words, apostrophes, and punctuation blocks. Word and sentence counts on Money Master Blog use standard whitespace and delimiter separation and provide close approximations for drafting purposes.
              </p>
            </div>

            <div className="p-4 bg-white border border-neutral-200 rounded-lg">
              <strong className="text-neutral-900 block text-xs uppercase tracking-wider mb-1">Placeholder Text Generator (Lorem Ipsum)</strong>
              <p className="text-xs text-neutral-600 leading-relaxed">
                Dummy text generated on this website is derived from historical Latin roots and scrambled dummy passages intended exclusively for visual spacing, typographical testing, and layout wireframing. It carries no semantic, linguistic, or factual meaning.
              </p>
            </div>

            <div className="p-4 bg-white border border-neutral-200 rounded-lg">
              <strong className="text-neutral-900 block text-xs uppercase tracking-wider mb-1">Random Password Generator</strong>
              <p className="text-xs text-neutral-600 leading-relaxed">
                Passwords are generated via browser-based CSPRNG (<code>window.crypto.getRandomValues</code>). While cryptographically randomized, overall credential security also depends on utilizing multi-factor authentication (MFA), password manager vaults, and avoiding password reuse across services.
              </p>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-lg font-bold text-neutral-900 mb-2">3. Blog Articles, Educational Guides & Tutorials</h2>
          <p>
            The 20 guides and workflow tutorials published on Money Master Blog are created for informational, educational, and general productivity purposes:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1.5 text-neutral-600">
            <li><strong>Software Variability:</strong> While spreadsheet formulas (e.g. <code>TRIM</code>, <code>SUBSTITUTE</code>, <code>REGEXREPLACE</code>) and text cleanup workflows are verified in current versions of Google Sheets and Microsoft Excel, differences in operating systems, international language locales, or custom corporate security configurations may impact behavior.</li>
            <li><strong>Backup Recommendation:</strong> Before performing large batch data updates, bulk text replaces, or deleting duplicates based on guide instructions, users should always preserve an unaltered backup of the original spreadsheet or document.</li>
            <li><strong>No Professional Warranties:</strong> The advice in our guides reflects 7 years of practical digital workflow experience by author Shahid Ali, but does not constitute formal enterprise software consulting, legal counsel, or security certification.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-bold text-neutral-900 mb-2">4. User Responsibility & Verification</h2>
          <p>
            Users are responsible for reviewing and verifying the outputs of any tool before relying on them for critical publishing deadlines, official submissions, or sensitive cryptographic deployments.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-neutral-900 mb-2">5. Questions & Discrepancy Reporting</h2>
          <p>
            If you notice a discrepancy, formula quirk, or have a suggestion to improve any tool's accuracy or clarity, please contact Shahid Ali through our Contact Us page or write to <code>contact@moneymasterblog.com</code>.
          </p>
        </div>
      </div>

      {/* Disclaimer Page Specific FAQ */}
      <FaqSection
        id="disclaimer-faq"
        title="Frequently Asked Questions About Website Accuracy & Scope"
        subtitle="Detailed clarifications on monitor calibrations, word processing discrepancies, and tool limitations."
        items={disclaimerFaqs}
      />
    </div>
  );
}
